title       = "sinanews"
baseURL     = "https://sinanews-cli-cli.tamnd.com/"
description = "Browse Sina News articles (新浪新闻)"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/sinanews-cli-cli"
